[statinfer.com](https://statinfer.com/)

In [2]:
import pandas as pd
import sklearn as sk
import numpy as np
import scipy as sp
from sklearn import tree
from sklearn.metrics import confusion_matrix

# Data Importing

In [3]:
#Importing dataset
car_train=pd.read_csv("data/Car_Accidents_IOT/train.csv")
car_test=pd.read_csv("data/Car_Accidents_IOT/test.csv")

In [4]:
car_train.columns

Index(['Fatal', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'S9', 'S10',
       'S11', 'S12', 'S13', 'S14', 'S15', 'S16', 'S17', 'S18', 'S19', 'S20',
       'S21', 'S22'],
      dtype='object')

In [5]:
features=list(car_train.columns[1:])
X_train=car_train[features]
y_train=car_train['Fatal']

# Decision Tree

In [6]:
###buildng Decision tree on the training data ####
clf = tree.DecisionTreeClassifier(max_depth=6)
clf.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=6)

## Decision Tree Results

In [7]:
#####predicting on test data ####
tree_predict_train=clf.predict(car_train[features])
tree_predict=clf.predict(car_test[features])

########Train Data Validation
cm1 = confusion_matrix(car_train[['Fatal']],tree_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

########Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],tree_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)


Confusion Matrix for Train data 
 [[4940 1376]
 [ 688 8105]]
Accuracy of Train data 
 0.8633926798596863
Confusion Matrix for test data 
 [[2985  907]
 [ 389 4784]]
Accuracy of test data 
 0.8570325427468285


# Random Forest

In [29]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=150, max_features=6, max_depth=10)
# n_estimators - Trees - As high as possible
# max_features - p - low ==>(sqrt(t))
# max_depth - Slightly higher than single tree
forest.fit(X_train,y_train)

RandomForestClassifier(max_depth=10, max_features=6, n_estimators=150)

## Random Forest Results

In [30]:
#####predicting on test data ####
Forest_predict_train=forest.predict(car_train[features])
Forest_predict=forest.predict(car_test[features])

########Train Data Validation
cm1 = confusion_matrix(car_train[['Fatal']],Forest_predict_train)
print("Confusion Matrix for Train data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of Train data \n", accuracy_tree)

########Test Data Validation
cm1 = confusion_matrix(car_test[['Fatal']],Forest_predict)
print("Confusion Matrix for test data \n", cm1)
total1=sum(sum(cm1))
accuracy_tree=(cm1[0,0]+cm1[1,1])/total1
print("Accuracy of test data \n", accuracy_tree)


Confusion Matrix for Train data 
 [[5471  845]
 [ 277 8516]]
Accuracy of Train data 
 0.9257396253888411
Confusion Matrix for test data 
 [[3248  644]
 [ 231 4942]]
Accuracy of test data 
 0.9034749034749034
