# Packages

In [12]:
import pandas as pd
import sklearn as sk
import numpy as np
import scipy as sp
from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
import time
from sklearn.ensemble import GradientBoostingClassifier
import xgboost
from xgboost.sklearn import XGBClassifier
from sklearn import preprocessing

# Data Importing

Dataset Background : https://www.kaggle.com/c/otto-group-product-classification-challenge/notebooks

In [13]:
ecom_prod_train=pd.read_csv("data/Ecom_Products_Menu/train.csv")
ecom_prod_test=pd.read_csv("data/Ecom_Products_Menu/test.csv")

In [14]:
print(ecom_prod_train.sample(10))
print(ecom_prod_test.sample(10))

          id  spec1  spec2  spec3  spec4  spec5  spec6  spec7  spec8  spec9  \
10802  13352      2      0      0      0      0      0      0      1      0   
33686  41585      0      3      5      5      0      0      0      0      0   
16527  20390      0      0      0      0      0      0      0      0      0   
2528    3108      0      1      0      0      1      0      0      2      0   
4020    4963      2      0      0      0      0      0      0      0      0   
12612  15577      0      0      1      2      0      0      0      1      2   
38537  47544      0      0      0      1      0      0      0      0      0   
38335  47293      0      0      0      0      0      0      0      0      0   
26216  32367      0      0      1      0      0      0      0      0      0   
38284  47227      0      0      0      0      0      1      0      0      1   

       ...  spec92  spec93  spec94  spec95  spec96  spec97  spec98  spec99  \
10802  ...       9       3       0       0       0  

In [15]:
#Frequency counts of the products
ecom_prod_train['Category'].value_counts()

Tablets          13079
Personal_Care    11452
Appliances        6863
Laptops           6466
Camara            3964
Accessories       2341
Ipod              2217
TV                2182
Mobiles           1558
Name: Category, dtype: int64

# Prepare Features, Train and Test data

In [16]:
features=list(ecom_prod_train.columns[1:101])
print("features \n", features)
X_train=ecom_prod_train[features]
y_train=ecom_prod_train['Category']

X_test=ecom_prod_test[features]
y_test=ecom_prod_test['Category']

features 
 ['spec1', 'spec2', 'spec3', 'spec4', 'spec5', 'spec6', 'spec7', 'spec8', 'spec9', 'spec10', 'spec11', 'spec12', 'spec13', 'spec14', 'spec15', 'spec16', 'spec17', 'spec18', 'spec19', 'spec20', 'spec21', 'spec22', 'spec23', 'spec24', 'spec25', 'spec26', 'spec27', 'spec28', 'spec29', 'spec30', 'spec31', 'spec32', 'spec33', 'spec34', 'spec35', 'spec36', 'spec37', 'spec38', 'spec39', 'spec40', 'spec41', 'spec42', 'spec43', 'spec44', 'spec45', 'spec46', 'spec47', 'spec48', 'spec49', 'spec50', 'spec51', 'spec52', 'spec53', 'spec54', 'spec55', 'spec56', 'spec57', 'spec58', 'spec59', 'spec60', 'spec61', 'spec62', 'spec63', 'spec64', 'spec65', 'spec66', 'spec67', 'spec68', 'spec69', 'spec70', 'spec71', 'spec72', 'spec73', 'spec74', 'spec75', 'spec76', 'spec77', 'spec78', 'spec79', 'spec80', 'spec81', 'spec82', 'spec83', 'spec84', 'spec85', 'spec86', 'spec87', 'spec88', 'spec89', 'spec90', 'spec91', 'spec92', 'spec93', 'spec94', 'spec95', 'spec96', 'spec97', 'spec98', 'spec99', 'spec10

# Decision Tree model

In [17]:
###buildng Decision tree on the training data ####
from sklearn import tree
tree = tree.DecisionTreeClassifier(max_depth=9)
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=9)

## Decision Tree Results

In [18]:
#Accuracy on train data
print("Decision Tree Results \n")
print("Accuracy on train data" , tree.score(X_train, y_train))
print("Accuracy on test data" , tree.score(X_test, y_test))

Decision Tree Results 

Accuracy on train data 0.6363672638761422
Accuracy on test data 0.6268288533514801


# Boosted Model

In [8]:
from sklearn.ensemble import GradientBoostingClassifier
boost=GradientBoostingClassifier(n_estimators=100,learning_rate=0.1, verbose=1) 
##fitting the gradient boost classifier
start_time = time.time()
boost.fit(X_train,y_train)
print("Time taken by GBM "+ str((time.time() - start_time))+ " Seconds")

      Iter       Train Loss   Remaining Time 
         1           1.6679            5.52m
         2           1.5254            5.55m
         3           1.4205            5.19m
         4           1.3357            5.04m
         5           1.2661            4.92m
         6           1.2069            4.80m
         7           1.1570            4.69m
         8           1.1147            4.65m
         9           1.0746            4.63m
        10           1.0392            4.53m
        20           0.8356            4.02m
        30           0.7398            3.82m
        40           0.6852            3.34m
        50           0.6487            2.82m
        60           0.6220            2.30m
        70           0.6009            1.76m
        80           0.5838            1.18m
        90           0.5694           35.49s
       100           0.5563            0.00s
Time taken by GBM 361.53383922576904 Seconds


## GBM Results

In [9]:
###predicting Gradient boosting model on the train Data
boost_predict_train=boost.predict(X_train)
cm1 = confusion_matrix(y_train,boost_predict_train)
print(cm1)

accuracy_train=f1_score(y_train, boost_predict_train, average='micro') 
print("train accuracy", accuracy_train)

[[ 1497   116    16    11   132    54   162    23   330]
 [   50  6328    91     5    24    74   174     0   117]
 [   21   196  3352     4     6    86   146     1   152]
 [    0     3     3  2144     7     0     4     0    56]
 [  124    18    11     1  2954     7     8    69  3274]
 [   32   225   271     9     5   767   149     2    98]
 [  108   188   126     1    13    50 10813    11   142]
 [   20     7     2    14   264     0    61   934   880]
 [   77    24    12    18  1377     8    32    94 11437]]
train accuracy 0.8025617493316308


In [10]:
###predicting Gradient boosting model on the test Data
boost_predict_test=boost.predict(X_test)
cm1 = confusion_matrix(y_test,boost_predict_test)
print(cm1)

accuracy_test=f1_score(y_test, boost_predict_test, average='micro') 
print("test accuracy", accuracy_test)

[[ 310   31    0    1   25    9   41    5   76]
 [  14 1456   31    1    3   20   49    0   27]
 [   3   41  849    2    0   27   38    0   31]
 [   0    0    0  498    1    0    0    1   22]
 [  21    6    4    0  682    0    2   23  800]
 [   6   68   78    0    4  150   36    0   29]
 [  38   38   37    1    2   10 2512    3   42]
 [   5    1    0    3   68    0   22  169  241]
 [  20    7    7    9  329    0    8   23 2640]]
test accuracy 0.7881932630146308


# XGB Model

In [11]:
#Creating XGB Friendly data and matrices
train_labels = y_train.values
train_labels = preprocessing.LabelEncoder().fit_transform(train_labels)
test_labels = y_test.values
test_labels = preprocessing.LabelEncoder().fit_transform(test_labels)

matrix_train = xgboost.DMatrix(X_train,label=train_labels)
matrix_test = xgboost.DMatrix(X_test,label=test_labels)

In [21]:
params = {
    'max_depth': 4, 
    'eta':0.1, #Learning Rate
    'eval_metric':'merror', # Multiclass classification error rate. 
    'tree_method' : 'auto', # use this with colab in gpu mode for faster training "gpu_hist"
    'num_class': 9
}

start_time = time.time()

model=xgboost.train(params=params,
                    dtrain=matrix_train,
                    num_boost_round=300,    #Number of trees
                    early_stopping_rounds=4, # Stop after 4 rounds, if test error doesn't improve. 
                    evals=[(matrix_test,'test')] 
                   )

print("Time taken by XGB "+ str((time.time() - start_time))+ " Seconds")

[0]	test-merror:0.31159
[1]	test-merror:0.29704
[2]	test-merror:0.29296
[3]	test-merror:0.28386
[4]	test-merror:0.28054
[5]	test-merror:0.27492
[6]	test-merror:0.27339
[7]	test-merror:0.26939
[8]	test-merror:0.26727
[9]	test-merror:0.26744
[10]	test-merror:0.26421
[11]	test-merror:0.26310
[12]	test-merror:0.26106
[13]	test-merror:0.26148
[14]	test-merror:0.26029
[15]	test-merror:0.25842
[16]	test-merror:0.25817
[17]	test-merror:0.25485
[18]	test-merror:0.25451
[19]	test-merror:0.25306
[20]	test-merror:0.25238
[21]	test-merror:0.25153
[22]	test-merror:0.25017
[23]	test-merror:0.24813
[24]	test-merror:0.24651
[25]	test-merror:0.24660
[26]	test-merror:0.24541
[27]	test-merror:0.24600
[28]	test-merror:0.24541
[29]	test-merror:0.24490
[30]	test-merror:0.24524
[31]	test-merror:0.24354
[32]	test-merror:0.24337
[33]	test-merror:0.24319
[34]	test-merror:0.24226
[35]	test-merror:0.24132
[36]	test-merror:0.24056
[37]	test-merror:0.23988
[38]	test-merror:0.23903
[39]	test-merror:0.23869
[40]	test-

## XGB Results

In [22]:
###prediction using XGB on the train Data
boost_predict_train=model.predict(matrix_train)
cm1 = confusion_matrix(train_labels,boost_predict_train)
print(cm1)

accuracy_train=f1_score(train_labels, boost_predict_train, average='micro') 
print("train accuracy", accuracy_train)

[[ 1453   130    12    11   140    40   157    26   372]
 [   41  6325    98     6    17    62   185     0   129]
 [   19   196  3337     3     5    85   160     2   157]
 [    0     3     3  2139     7     0     3     0    62]
 [  115    23    17     0  2714     5     7    42  3543]
 [   31   267   334     8     9   659   149     2    99]
 [  120   203   146     1    17    45 10753     9   158]
 [   30     5     2    19   238     0    65   846   977]
 [   65    25    13    16  1176     5    27    71 11681]]
train accuracy 0.7961972786401181


In [23]:
###prediction using XGB on the test Data
boost_predict_test=model.predict(matrix_test)
cm1 = confusion_matrix(test_labels,boost_predict_test)
print(cm1)

accuracy_test=f1_score(test_labels, boost_predict_test, average='micro') 
print("test accuracy", accuracy_test)

[[ 306   32    1    1   33    9   39    4   73]
 [  13 1466   32    1    1   12   44    0   32]
 [   2   43  842    2    3   22   43    1   33]
 [   0    1    0  498    0    1    0    1   21]
 [  29    7    5    0  586    0    1   12  898]
 [   8   80   87    0    5  133   33    0   25]
 [  35   37   41    1    6   11 2507    1   44]
 [   9    1    0    4   62    0   22  159  252]
 [  20    7    7    9  296    0    7   20 2677]]
test accuracy 0.7803674719292276
